import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState, useRef, useEffect } from "react";
import bannerImage from "../public/bannerImage.png";
import { AiOutlineCopyrightCircle } from "react-icons/ai";
import { CgArrowLongRight } from "react-icons/cg";

export const Blog = () => {
  const [items, setItems] = useState([]);
  const [visible, setVisible] = useState(4);

  async function fetchData() {
    const response = await axios.get(
      "https://frontend-case-api.sbdev.nl/api/posts?page=1&perPage=5",
      {
        headers: {
          "Content-Type": "application/json",
          token: "pj11daaQRz7zUIH56B9Z",
        },
      }
    );
    setItems(response.data.data);
  }

  useEffect(() => fetchData(), []);
  console.log(items);

  const [pagination, setPagination] = useState([]);

  async function fetchPagination() {
    const response = await axios.get(
      "https://frontend-case-api.sbdev.nl/api/posts?page=1&perPage=5",
      {
        headers: {
          "Content-Type": "application/json",
          token: "pj11daaQRz7zUIH56B9Z",
        },
      }
    );
    setPagination(response.data.links);
  }

  useEffect(() => fetchPagination(), []);
  console.log(pagination);

  const first = pagination.slice(1, 6);
  const second = pagination.slice(11, 12);
  const third = pagination.slice(12, 14);

  const paginationAlmostTogheter = first.concat(second);
  const paginationSliced = paginationAlmostTogheter.concat(third);

  console.log("splicing", paginationSliced);

  return (
    <div className="flex flex-col items-center">
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <div className="imageSize">
        <Image src={bannerImage} alt="Banner Image" />
      </div>

      <div id="pageWidthBlog">
        <div className="BlogBackground m-12">
          <div className=" m-6 pt-6 grid grid-cols-1 sm:grid-cols-4 gap-6">
            {items.slice(0, visible).map((item) => (
              <div class="card bg-white overflow-hidden flex flex-col md:flex-row ">
                <div>
                  <div className="cardImage relative">
                    <img src={item.img_url} />
                    <div className="Pos flex flex-row justify-between items-end m-2 mt-8 z-10">
                      <p id="cardImageText">{item.created_at.split("T")[0]}</p>
                      <p id="cardImageText">{item.category.name}</p>
                    </div>
                  </div>
                  <div className="cardTextSize m-4">
                    <h1>{item.title}</h1>
                    <p>{item.content}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="m-6 grid grid-cols-1 sm:grid-cols-4 gap-6">
            {items.slice(0, visible).map((item) => (
              <div class="card bg-white overflow-hidden flex flex-col md:flex-row ">
                <div>
                  <div className="cardImage relative">
                    <img src={item.img_url} />
                    <div className="Pos flex flex-row justify-between items-end m-2 mt-8 z-10">
                      <p id="cardImageText">{item.created_at.split("T")[0]}</p>
                      <p id="cardImageText">{item.category.name}</p>
                    </div>
                  </div>
                  <div className="cardTextSize m-4">
                    <h1>{item.title}</h1>
                    <p>{item.content}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="flex flex-row justify-center items-center content-center">
            <div className="letters flex flex-row m-4">
              {paginationSliced.map((page) => (
                <div>
                  <a className="paginationStyle m-2" href={page.url}>
                    {page.label}
                  </a>
                </div>
              ))}
            </div>
            <a
              href="https://frontend-case-api.sbdev.nl/api/posts?page=4"
              className="paginationText m-1"
            >
              Volgende pagina
            </a>
            <CgArrowLongRight color="#F27623" fontSize="0.75em" />
          </div>
        </div>
        <footer className="footer">
          <AiOutlineCopyrightCircle />
          <p className="footerText">Copyright Social Brothers - 2020</p>
        </footer>
      </div>
    </div>
  );
};

export default Blog;
